apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend

spec:
  replicas: 1

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
      - name: backend

        image: 839931788751.dkr.ecr.us-east-2.amazonaws.com/eks-demo-dev-backend:v1

        ports:
        - containerPort: 5000